### ISSUE TITLE
Wartung von Auswahlfelder ermöglichen

### ISSUE THREAD

**Issue by SigurdJanson** [SigurdJanson/fragebogenmatrix#1]
Einige unsere Felder zur Beschreibung der Fragebögen werden direkt in die Datenbank geschrieben. Sie werden aber nicht korrigiert, wenn man die Felder ändert (z.B. nach einem Schreibfehler) und sie werden auch nicht entfernt, wenn man sie löscht. Jetzt haben wir dutzende unnötiger Felder. Die machen es den Nutzern schwer das richtige Stichwort zu suchen.

- Kurzfristige Lösung: nicht benötigte Felder aus der Datenbank entfernen.
- Längerfrsitig (Prio 2): entweder versteht das System von selbst, welche Begriffe verwendet werden und zeigt den Nutzern auch nur diese in der Dropdown an; oder wir können Begriffe händisch bearbeiten.

**Comment by SigurdJanson** [comment]
Möglicherweise eine Frage der Rechte in Drupal. Michael klärt das.

**Comment by jendryschik** [comment]
Ich lasse im CMS eine Rolle einrichten, die Zugriff auf die Fragebogen-Taxonomien hat, dann könnt ihr oder eine*r von euch alles selbst pflegen.

**Comment by jendryschik** [comment]
Hier sind die Einsatzfelder: https://germanupa.de/admin/structure/taxonomy/manage/fragebogen_einsatzfelder/overview
Hier die Dimensionen: https://germanupa.de/admin/structure/taxonomy/manage/fragebogen_gemessene_dimension/overview
Und hier die Sprachen: https://germanupa.de/admin/structure/taxonomy/manage/fragebogen_sprache/overview

**Comment by SigurdJanson** [comment]
Funktioniert. Ist noch mühsam und unübersichtlich und evtl. kommen wir wieder mit Sonderwünschen zurück, weil uns die Übersicht fehlt. Aber grundsätzlich können wir tun, was wir tun müssen.
