### ISSUE TITLE
Die Breadcrumb ist noch nicht konsistent

### ISSUE THREAD

**Issue by SigurdJanson** [SigurdJanson/fragebogenmatrix#12]
Wenn auf Fragebogendetails, dann müsste die Matrix eigentlich in der Breadcrumb mit auftauschen. Tut sie aber nicht. Siehe Bild.

![grafik](https://user-images.githubusercontent.com/59577271/130816770-1ac67c72-4e0c-43fb-b15b-bb5023c42125.png)

**Comment by jendryschik** [comment]
Der Bug wird im Rahmen des laufenden germanupa.de-Relaunch-Projekts gefixt werden.
Die Breadcrumbs stimmen an vielen Stellen nicht; das ist ein generelles Problem.
