### ISSUE TITLE
Kommentare managen

### ISSUE THREAD

**Issue by SigurdJanson** [SigurdJanson/fragebogenmatrix#2]
Man kann Fragebögen in der Matrix kommentieren. Aber wir kriegen diese Kommentare nicht wieder weg. Jetzt haben wir einige Testkommentare (v.a. beim VisAWI weiß ich das: https://www.germanupa.de/fragebogenmatrix/visawi) und die müssten entfernt werden.

- Ich empfehle so schnell wie möglich ein Captcha einzubauen für alle nicht-angemeldeten Nutzer. Sobald man sich als UPA Mitglied registriert hat könnte das natürlich entfallen.
- Langfristig brauchen wir eine Möglichkeit, Kommentare zu bearbeiten und zu löschen, allein, um gegen Trolle und Werbung vorzugehen oder um veraltete Inhalte zu entfernen.

**Comment by jendryschik** [comment]
Sicher, dass es Kommentare gibt? Auf https://www.germanupa.de/wissen/fragebogenmatrix/visawi sehe ich keinen.

**Comment by SigurdJanson** [comment]
Scheint mit dem Relaunch entfernt worden zu sein. Jetzt fehlt eine Kontaktmöglichkeit. Dieses issue ist erledigt. Siehe auch #15
