### ISSUE TITLE
Bug: Dropdown-Felder in den Filter werden zu Listboxen und zerstören das Layout

### ISSUE THREAD

**Issue by SigurdJanson** [SigurdJanson/fragebogenmatrix#3]
Es gibt noch einen Bug bei den Filtern. Wenn ich einen Filter an-/abwähle, werden aus den Dropdown-Listen auf einmal Listboxen. Das kann unmöglich so bleiben.

**Comment by jendryschik** [comment]
Ich habe den Dienstleister beauftragt, die Darstellung schnell zu fixen, indem es wieder drei gleich breite, nebeneinander stehende Dropdown-Listen werden, aus denen der Nutzer jeweils einen Eintrag auswählen kann. Das kann aber nicht die beste Darstellung sein, denn vielleicht möchte ein Nutzer ja jeweils mehrere Kriterien wählen? Etwa wie in einem Online-Shop, z.B. hier: https://www.mey-edlich.de/shirts/c/82.02?followSearch=9999&allPages=0&facetsSort=null-desc&f_Groesse=NORMAL--50&f_Groesse=NORMAL--52&f_Farbgruppe=grau&f_Farbgruppe=schwarz&f_Preis=%3C%3D%20100

Möchtet ihr euch da etwas überlegen und vorschlagen (Mockup mit Wunsch-Darstellung)?

**Comment by jendryschik** [comment]
Der Bug wurde mittlerweile gefixt.
