### ISSUE TITLE
Vorlage beim Editieren

### ISSUE THREAD

**Issue by SigurdJanson** [SigurdJanson/fragebogenmatrix#9]
Ergänzung von beispielhaften Inhalten - mir schwebt ein Template vor, dass man nur noch ändern muss und das einem zeigt, wie die Inhalte aussehen könnten. Dazu können wir Euch dann noch mehr Input liefern.

Ziele:
- Arbeitserleichterung.
- Anweisungen bzgl erwarteten Inhalten.
- Formatierungsanweisungen direkt an Ort und Stelle, die der Autor nicht suchen muss.
- Konsistenz der Inhalte.

**Comment by jendryschik** [comment]
Das CMS wird nach dem Relaunch die Möglichkeit bieten, Inhalte zu klonen. So könntet ihr ein Template mit Beispielen und Hilfetexten anlegen und einen Klon davon als Grundlage bei der Erstellung weiterer Fragebögen verwenden.

**Comment by jendryschik** [comment]
Das geht hier über Duplizieren.

![image](https://user-images.githubusercontent.com/637900/146992334-ee0977af-fb0b-4a75-a33b-75a39f9604d7.png)

Also einfach ein Fragebogendetails-Template anlegen und immer wiederverwenden.

**Comment by SigurdJanson** [comment]
@SigurdJanson Template anlegen
